# Generated by Django 5.0.7 on 2024-10-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('CARD', 'Credit or Cheque Card'), ('BANK', 'Pay by Bank'), ('CAPITEC', 'Capitec Pay')], max_length=20)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('cvv', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
    ]
