# Generated by Django 5.0.7 on 2024-09-27 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('reserve_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crop_type', models.CharField(choices=[('Grain', 'Grain'), ('Vegetable', 'Vegetable'), ('Fruit', 'Fruit'), ('Legume', 'Legume'), ('Tubers', 'Tubers')], max_length=50)),
                ('variety', models.CharField(blank=True, choices=[('Wheat', 'Wheat'), ('Rice', 'Rice'), ('Barley', 'Barley'), ('Carrot', 'Carrot'), ('Spinach', 'Spinach'), ('Broccoli', 'Broccoli'), ('Apple', 'Apple'), ('Banana', 'Banana'), ('Orange', 'Orange'), ('Peas', 'Peas'), ('Lentils', 'Lentils'), ('Beans', 'Beans'), ('Potato', 'Potato'), ('Sweet Potato', 'Sweet Potato'), ('Yam', 'Yam')], max_length=50)),
                ('season', models.CharField(max_length=50)),
                ('harvest_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='crops/')),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('maintenance_task', models.CharField(choices=[('Check-up', 'Check-up'), ('Servicing', 'Servicing'), ('Replacement', 'Replacement')], max_length=50)),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Cattle', 'Cattle'), ('Sheep', 'Sheep'), ('Pigs', 'Pigs'), ('Goats', 'Goats'), ('Horses', 'Horses')], max_length=20)),
                ('breed', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('milkproduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pregnant', models.CharField(max_length=100)),
                ('healthStatus', models.TextField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='crops/')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='crops/')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='signup.auction')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bid_time', models.DateTimeField(auto_now_add=True)),
                ('auction_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='signup.auctionitem')),
            ],
        ),
    ]
