# Generated by Django 5.0.7 on 2024-09-28 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_alter_auction_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='auction_item',
        ),
        migrations.DeleteModel(
            name='Auction',
        ),
        migrations.DeleteModel(
            name='AuctionItem',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
