# Generated by Django 5.0.7 on 2024-09-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crop_type', models.CharField(max_length=100)),
                ('variety', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=50)),
                ('harvest_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='crops/')),
            ],
        ),
    ]
