# Generated by Django 5.0.7 on 2024-09-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, max_length=50)),
                ('milkproduction', models.DecimalField(decimal_places=2, max_digits=10, max_length=50)),
                ('pregnant', models.CharField(max_length=100)),
                ('healthStatus', models.TextField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='crops/')),
            ],
        ),
    ]
