# Generated by Django 5.0.7 on 2024-09-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_livestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestock',
            name='type',
            field=models.CharField(choices=[('pig', 'Pig'), ('cow', 'Cow'), ('goat', 'Goat'), ('horse', 'Horse'), ('sheep', 'Sheep')], default='pig', max_length=10),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='milkproduction',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
