# Generated by Django 5.0.7 on 2024-09-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_livestock_type_alter_livestock_milkproduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestock',
            name='breed',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='type',
            field=models.CharField(choices=[('Cattle', 'Cattle'), ('Sheep', 'Sheep'), ('Pigs', 'Pigs'), ('Goats', 'Goats'), ('Horses', 'Horses')], max_length=20),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
