# Generated by Django 5.0.7 on 2024-09-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_livestock_breed_alter_livestock_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/crops/'),
        ),
    ]
