# Generated by Django 5.0.7 on 2024-09-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auction_auctionitem_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='crops/'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='crops/'),
        ),
    ]
