# Generated by Django 5.0.7 on 2024-09-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auctionitem_image_alter_livestock_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
