# Generated by Django 5.0.7 on 2024-09-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_crop_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='crop_type',
            field=models.CharField(choices=[('Grain', 'Grain'), ('Vegetable', 'Vegetable'), ('Fruit', 'Fruit'), ('Legume', 'Legume'), ('Tubers', 'Tubers')], max_length=50),
        ),
        migrations.AlterField(
            model_name='crop',
            name='variety',
            field=models.CharField(blank=True, choices=[('Wheat', 'Wheat'), ('Rice', 'Rice'), ('Barley', 'Barley'), ('Carrot', 'Carrot'), ('Spinach', 'Spinach'), ('Broccoli', 'Broccoli'), ('Apple', 'Apple'), ('Banana', 'Banana'), ('Orange', 'Orange'), ('Peas', 'Peas'), ('Lentils', 'Lentils'), ('Beans', 'Beans'), ('Potato', 'Potato'), ('Sweet Potato', 'Sweet Potato'), ('Yam', 'Yam')], max_length=50),
        ),
    ]
