# Generated by Django 5.0.7 on 2024-09-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_crop_crop_type_alter_crop_variety'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('maintenance_task', models.CharField(choices=[('Check-up', 'Check-up'), ('Servicing', 'Servicing'), ('Replacement', 'Replacement')], max_length=50)),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=50)),
            ],
        ),
    ]
