# Generated by Django 5.0.7 on 2024-09-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_equipment'),
    ]

    operations = [
    ]
