# Generated by Django 5.0.7 on 2024-09-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='employee_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff')], default='customer', max_length=10),
        ),
    ]
