# Generated by Django 5.0.7 on 2024-09-23 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_customuser_employee_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
