# Generated by Django 5.0.7 on 2024-09-28 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crop',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='Livestock',
        ),
    ]
