# Generated by Django 5.0.4 on 2024-10-04 02:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_delete_crop_delete_employee_delete_equipment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='auction',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='auction',
            name='image',
            field=models.ImageField(blank=True, default='images/images.jpg', null=True, upload_to='auction_images/'),
        ),
        migrations.AddField(
            model_name='auction',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='auction',
            name='reserve_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='auction',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
