# Generated by Django 5.0.4 on 2024-10-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(blank=True, default='crops/default.jpg', null=True, upload_to='crops/'),
        ),
    ]
